### ISSUE TITLE
Doesnt work for me

### ISSUE THREAD

**Issue by sepulchre** [answerquest/answerquest.github.io#2]
Hey, does this also work for whole channel videos and not just playlist?
In your html:
https://answerquest.github.io/youtube-all-vids-info.html

I can only type playlist, but I want to list all videos of a youtube channel, like all  2569 videos or something.

I know that this might not be an issue but I didnt know how else I can contact you or ask a question.

Thanks.

**Comment by answerquest** [comment]
Hi @sepulchre, that's precisely why I made the script! So the thing is, youtube makes a 'default' playlist for every channel (they call this playlist "uploads") which holds ALL the non-private videos of that channel.

The default playlist Id I'm featuring on the page (`UUT7EcU7rC44DiS3RkfZzZMg`) is the `uploads` of `Arvind Gupta Toys` channel. Click the "click here to find playlist id" link. In the api page that opens, put in your target channel's username or channel-id in place of what I've put in. Turn on all the authorization stuff (with your google account of course), run it and see the results. Over there you'll see a JSON array like so:
```
"relatedPlaylists": {
     "favorites": "FLT7EcU7rC44DiS3RkfZzZMg",
     "uploads": "UUT7EcU7rC44DiS3RkfZzZMg",
     "watchHistory": "HL",
     "watchLater": "WL"
```
The value next to 'uploads' is what you want. Get back to the script, put this value in for `Uploads Playlist Id`. Hope this works out for you :+1:

**Comment by sepulchre** [comment]
Hello,

I apologize for a very late reply.

When I do what you describe, I always get no array, like this:

{
 "pageInfo": {
  "totalResults": 0
 },
 "items": [
 ]
}

Now further testing shows me what the problem is. If you enter channel ID, you get no answer, if you enter channel name, like you did, you get an answer. Probably it is a bug?
Can you confirm it is working for you when you enter channel ID to get JSON response? For me it is not working.

Thank you and have a nice day.

**Comment by answerquest** [comment]
Hi @sepulchre , there is a separate input field in the google api page for entering channel name (**_forUsername_**), and a separate one for entering channel id (**_id_**, just two places below ). You can put in any one. Obviously if you put the id into the username field it's not going to work. And that is  Google's Youtube API page, go tell them if you think it's a bug. On my page there's no username or user id to enter; you have to find the channel's uploads playlist and enter that.
