### ISSUE TITLE
Buttons don't work

### ISSUE THREAD

**Issue by sepulchre** [answerquest/answerquest.github.io#3]
https://answerquest.github.io/youtube-all-vids-info.html

For this after I get the basic listing, when I click on "Download CSV", nothing happens.

Or after I do the "Full vids info", after the fetching, when I click on the detailed data buttons none of them work. Nothing happens.

I'm using Firefox Quantum 59.0.1 with Win 8.1

**Comment by answerquest** [comment]
Hi @sepulchre, check your default downloads folder? Can you open the browser console and run the page and paste the output here? The script is set to save the csv / json with a preset filename. If your browser hasn't been set to ask you each time where to save, it will be saving it in your downloads folder. In firefox it doesn't show very visibly.. the downloads button at top becomes blue thats all.

**Comment by sepulchre** [comment]
There is nothing in my default downloads folder. Nothing happens at all.

I also opened the browser console, for 200 entries it makes 4 GET requests, then for the extended one 200 GET requests and all is good. But no action, nothing when I click on the buttons, nothing to see in the console.

But here it is, I am gonna test with IE after this message to see if it is the browser.
edit: Same with IE, no button works.
```
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead[Weitere Informationen]
jquery.min.v1.10.2.js:1
Unbekannte Eigenschaft 'user-select'.  Deklaration ignoriert.
s3downbar.css:34:14
Unbekannte Eigenschaft 'user-select'.  Deklaration ignoriert.
s3downbar.css:199:14
Fehler beim Verarbeiten des Wertes für 'background-position'.  Deklaration ignoriert.
s3downbar.css:332:28
Fehler beim Verarbeiten des Wertes für 'min-height'.  Deklaration ignoriert.
s3downbar.css:352:14
Unbekannte Eigenschaft 'user-select'.  Deklaration ignoriert.
tooltip.css:66:14
Source-Map-Fehler: request failed with status 404
Ressourcen-Adresse: https://answerquest.github.io/lib/jquery.min.v1.10.2.js
Source-Map-Adresse: jquery.min.map[Weitere Informationen]
GETXHR
https://www.googleapis.com/youtube/v3/playlistItems
[HTTP/2.0 200 OK 520ms]
GETXHR
https://www.googleapis.com/youtube/v3/playlistItems
[HTTP/2.0 200 OK 180ms]
...
keeps repeating, no need to copy-paste more
```

**Comment by answerquest** [comment]
Ah yes I think this file saving code doesn't work in Firefox.. works in Chrome / Chromium. If you can fix it then please fork and fix, I don't have time at the moment. I came across other limits: with a channel whose total count was over 10k, the file saving action crashed the browser. So at some point I need to work on sequentially saving files every 1000 videos or so, clearing out the memory and proceeding.
