### ISSUE TITLE
Is this Code Correct. Please Check from UP to Down...Please... I make it from your youtube file ....... please let me correct any wrong thing

### ISSUE THREAD

**Issue by siradhana** [answerquest/answerquest.github.io#6]
I have attached the file........ please check sir... and please tell me if ........ all code is correct or something missing or wrong or extra added or not required added ???

[list yt playlist videos infinite.txt](https://github.com/answerquest/answerquest.github.io/files/3533279/list.yt.playlist.videos.infinite.txt)

please help sir, please cross check for right or wrong.......... i am waiting sir............ please

**Comment by answerquest** [comment]
Hi @siradhana , sorry I will not be able to figure anything out and I don't have time on hand to go deeper into your issue. The code doesn't seem enough; I don't think you even have the html properly formed.

**Comment by siradhana** [comment]
sir, actually i did not html body tags  ....

all i add is the code that i want you to check

please.... tell me if the function i am using is right ... or wrong....

please sir...


its only of few lines


sir please

**Comment by answerquest** [comment]
@siradhana you have not even shared precisely what your code is intended for. Sorry, I cannot help you and really I don't have time for this sort of thing - please go ask on other forums to other people. And please look around on github and stackoverflow.. you have to keep things professional around here as what you post is public and later on people searching you on google will find this.

**Comment by siradhana** [comment]
Ok sir... :(

Actually code i shared is for fetching youtube playlist videos.... Using auto pagination ...... Its based on your youtube script ... That you shared in answerquest...

:(
